// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lobby-neon/Neon.tsx": () => import("../components/mockups/lobby-neon/Neon.tsx"),
  "./components/mockups/lobby-void/Void.tsx": () => import("../components/mockups/lobby-void/Void.tsx"),
  "./components/mockups/lobby-warm/Warm.tsx": () => import("../components/mockups/lobby-warm/Warm.tsx")
};
