// Re-exported from @workspace/shared — the canonical source of truth is
// lib/shared/src/collisionData.ts. Edit that file (or run the analysis script)
// to update the collision grid; do not edit this file directly.
//
// The in-app Collision Editor writes to lib/shared/src/collisionData.ts via
// the Vite dev middleware endpoint in vite.config.ts.
export { CELL, COLS, ROWS, RUNS } from '@workspace/shared/collisionData';
