// ─────────────────────────────────────────────────────────────────────────────
// Collision map for the 1040 × 580 top-down game map.
//
// The grid is decoded from `collisionData.ts`, which is generated by
// `scripts/src/analyzeCollisionMap.ts` directly from the pixel data of the
// red-line reference image (attached_assets/IMG_2907_1783593845208.jpeg).
// It is pixel-accurate: every red boundary line and every obstacle fully
// enclosed by its own red outline (furniture, vehicles, machinery, planters)
// is traced from the actual artwork rather than hand-approximated rectangles.
// Re-run that script if the reference image ever changes.
//
// Grid: COLS columns × ROWS rows, each cell = CELL × CELL px.
//   col = Math.floor(px / CELL)   row = Math.floor(py / CELL)
//
// Values:  0 = walkable    1 = blocked / wall
// ─────────────────────────────────────────────────────────────────────────────

import { CELL, COLS, ROWS, RUNS } from './collisionData';

export const MAP_W = 1040;
export const MAP_H = 580;
export { CELL, COLS, ROWS };

export type Grid = Uint8Array;

/** Decode the RLE-encoded pixel-accurate grid produced from the reference image. */
function decodeRuns(): Grid {
  const g = new Uint8Array(COLS * ROWS);
  let i = 0;
  let v: 0 | 1 = 0;
  for (const runLen of RUNS) {
    for (let k = 0; k < runLen; k++) g[i++] = v;
    v = v === 0 ? 1 : 0;
  }
  if (i !== COLS * ROWS) {
    throw new Error(
      `collisionData.ts RUNS decode length mismatch: got ${i} cells, expected ${COLS * ROWS}. ` +
      `Re-run scripts/src/analyzeCollisionMap.ts to regenerate it.`,
    );
  }
  return g;
}

// ─────────────────────────────────────────────────────────────────────────────
// Room / zone descriptors
// ─────────────────────────────────────────────────────────────────────────────
export type ZoneName =
  | 'garage_nw'
  | 'industrial'
  | 'pipe_corridor'
  | 'lobby'
  | 'tech_room_ne'
  | 'ne_connector'
  | 'far_right_top'
  | 'office_e'
  | 'far_right_strip'
  | 'gas_station'
  | 'park'
  | 'junction_s'
  | 'garage_se'
  | 'corridor_se'
  | 'electrical'
  | 'strip_far_se';

export interface Zone {
  name: ZoneName;
  label: string;
  /** pixel bounds */
  px: number; py: number; pw: number; ph: number;
}

// Approximate labeled regions for the debug-overlay hover UI only — these are
// coarse boxes for display purposes and are NOT used by collision/movement
// logic (that comes entirely from the pixel-accurate grid above). Re-eyeball
// against a fresh screenshot with the overlay on if the reference image
// changes noticeably.
export const ZONES: Zone[] = [
  { name: 'garage_nw',      label: 'Parking Garage',      px:   0, py:   0, pw: 270, ph: 180 },
  { name: 'industrial',     label: 'Boiler Room',          px:   0, py: 180, pw: 310, ph: 210 },
  { name: 'pipe_corridor',  label: 'Pipe Corridor',        px:   0, py: 210, pw:  45, ph: 180 },
  { name: 'lobby',          label: 'Main Lobby / Atrium',  px: 280, py:   0, pw: 430, ph: 390 },
  { name: 'tech_room_ne',   label: 'Tech Room',            px: 710, py:   0, pw: 170, ph: 190 },
  { name: 'ne_connector',   label: 'NE Connector',         px: 670, py:  80, pw:  50, ph: 110 },
  { name: 'far_right_top',  label: 'Far-Right Upper',      px: 880, py:   0, pw: 160, ph:  80 },
  { name: 'office_e',       label: 'East Office',          px: 780, py: 190, pw: 170, ph: 200 },
  { name: 'far_right_strip',label: 'Far-Right Strip',      px: 950, py:  80, pw:  90, ph: 310 },
  { name: 'gas_station',    label: 'Gas Station',          px:   0, py: 390, pw: 310, ph: 190 },
  { name: 'park',           label: 'Outdoor Park',         px: 310, py: 390, pw: 400, ph: 190 },
  { name: 'junction_s',     label: 'South Junction',       px: 600, py: 360, pw: 130, ph: 130 },
  { name: 'garage_se',      label: 'Vehicle Garage',       px: 730, py: 330, pw: 140, ph: 160 },
  { name: 'corridor_se',    label: 'SE Corridor',          px: 870, py: 210, pw:  50, ph: 280 },
  { name: 'electrical',     label: 'Electrical Room',      px: 730, py: 470, pw: 190, ph: 110 },
  { name: 'strip_far_se',   label: 'Far-SE Strip',         px: 920, py: 320, pw: 120, ph: 260 },
];

// ─────────────────────────────────────────────────────────────────────────────
// Build the static collision grid
// ─────────────────────────────────────────────────────────────────────────────
let _cached: Grid | null = null;

export function buildCollisionGrid(): Grid {
  if (_cached) return _cached;
  // Decoded directly from the red-line reference image (see
  // scripts/src/analyzeCollisionMap.ts) — pixel-accurate, not hand-traced.
  _cached = decodeRuns();
  return _cached;
}

// ─────────────────────────────────────────────────────────────────────────────
// Query helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Is the cell at pixel (px, py) blocked? Returns true if outside map bounds. */
export function isBlocked(grid: Grid, px: number, py: number): boolean {
  const col = Math.floor(px / CELL);
  const row = Math.floor(py / CELL);
  if (col < 0 || col >= COLS || row < 0 || row >= ROWS) return true;
  return grid[row * COLS + col] === 1;
}

/**
 * Can an entity with the given radius move to pixel position (cx, cy)?
 * Samples the center plus points around the circle's circumference — not
 * just the 4 cardinal points — so corners of blocked cells can't be cut
 * through during diagonal movement. Sample count scales with radius so the
 * arc length between samples stays well under one grid cell.
 */
export function canMoveTo(
  grid: Grid,
  cx: number, cy: number,
  radius = 8,
): boolean {
  if (isBlocked(grid, cx, cy)) return false;

  const samples = Math.max(8, Math.ceil((2 * Math.PI * radius) / (CELL * 0.5)));
  for (let i = 0; i < samples; i++) {
    const angle = (i / samples) * Math.PI * 2;
    const px = cx + Math.cos(angle) * radius;
    const py = cy + Math.sin(angle) * radius;
    if (isBlocked(grid, px, py)) return false;
  }
  return true;
}

/**
 * Resolve movement: return the furthest reachable position when trying to
 * move from (x, y) to (nx, ny) with the given radius.  Slides along walls
 * by trying each axis independently.
 */
export function resolveMovement(
  grid: Grid,
  x: number,  y: number,
  nx: number, ny: number,
  radius = 8,
): [number, number] {
  // Try full move
  if (canMoveTo(grid, nx, ny, radius)) return [nx, ny];
  // Slide on X only
  if (canMoveTo(grid, nx, y, radius))  return [nx, y];
  // Slide on Y only
  if (canMoveTo(grid, x, ny, radius))  return [x, ny];
  // Stuck
  return [x, y];
}
