// ─────────────────────────────────────────────────────────────────────────────
// Collision map for the 1040 × 580 top-down game map.
//
// The grid is decoded from `collisionData.ts`, which is generated by
// `scripts/src/analyzeCollisionMap.ts` directly from the pixel data of the
// red-line reference image (attached_assets/IMG_2907_1783593845208.jpeg).
// It is pixel-accurate: every red boundary line and every obstacle fully
// enclosed by its own red outline (furniture, vehicles, machinery, planters)
// is traced from the actual artwork rather than hand-approximated rectangles.
// Re-run that script if the reference image ever changes.
//
// Grid: COLS columns × ROWS rows, each cell = CELL × CELL px.
//   col = Math.floor(px / CELL)   row = Math.floor(py / CELL)
//
// Values:  0 = walkable    1 = blocked / wall
// ─────────────────────────────────────────────────────────────────────────────

import { CELL as _CELL, COLS, ROWS, RUNS } from './collisionData';

// Upscale factor applied on top of the previous 1652×952 canvas.
const _UPSCALE = 1.5;
export const MAP_W = Math.round(1652 * _UPSCALE); // 2478
export const MAP_H = Math.round(952 * _UPSCALE);  // 1428
export { COLS, ROWS };

/**
 * Pixel size of one collision cell in each axis.
 * The underlying grid was built at COLS×ROWS cells from a 1040×580 reference
 * (CELL=10 px/cell), but the visual map is now 1652×952, so X and Y cell
 * sizes differ slightly. All pixel-space ↔ grid-space conversions use these.
 */
export const CELL_X = MAP_W / COLS;   // ≈ 15.885 px
export const CELL_Y = MAP_H / ROWS;   // ≈ 16.414 px

// Keep CELL as the average for code that needs a single representative value
// (e.g. sample-count calculations in canMoveTo).
export const CELL = (_CELL * MAP_W) / (COLS * _CELL); // same as MAP_W/COLS

export type Grid = Uint8Array;

/** Decode the RLE-encoded pixel-accurate grid produced from the reference image. */
function decodeRuns(): Grid {
  const g = new Uint8Array(COLS * ROWS);
  let i = 0;
  let v: 0 | 1 = 0;
  for (const runLen of RUNS) {
    for (let k = 0; k < runLen; k++) g[i++] = v;
    v = v === 0 ? 1 : 0;
  }
  if (i !== COLS * ROWS) {
    throw new Error(
      `collisionData.ts RUNS decode length mismatch: got ${i} cells, expected ${COLS * ROWS}. ` +
      `Re-run scripts/src/analyzeCollisionMap.ts to regenerate it.`,
    );
  }
  return g;
}

// ─────────────────────────────────────────────────────────────────────────────
// Room / zone descriptors
// ─────────────────────────────────────────────────────────────────────────────
export type ZoneName =
  | 'garage_nw'
  | 'industrial'
  | 'pipe_corridor'
  | 'lobby'
  | 'tech_room_ne'
  | 'ne_connector'
  | 'far_right_top'
  | 'office_e'
  | 'far_right_strip'
  | 'gas_station'
  | 'park'
  | 'junction_s'
  | 'garage_se'
  | 'corridor_se'
  | 'electrical'
  | 'strip_far_se';

export interface Zone {
  name: ZoneName;
  label: string;
  /** pixel bounds */
  px: number; py: number; pw: number; ph: number;
}

// Approximate labeled regions for the debug-overlay hover UI only — these are
// coarse boxes for display purposes and are NOT used by collision/movement
// logic (that comes entirely from the pixel-accurate grid above). Re-eyeball
// against a fresh screenshot with the overlay on if the reference image
// changes noticeably.
// Zone bounds were originally measured against the 1040×580 canvas.
// Scale them to the current MAP_W×MAP_H canvas using the same X/Y ratios.
const _SX = MAP_W / 1040;
const _SY = MAP_H / 580;
const z = (px: number, py: number, pw: number, ph: number): Pick<Zone, 'px'|'py'|'pw'|'ph'> => ({
  px: Math.round(px * _SX), py: Math.round(py * _SY),
  pw: Math.round(pw * _SX), ph: Math.round(ph * _SY),
});

export const ZONES: Zone[] = [
  { name: 'garage_nw',       label: 'Parking Garage',      ...z(  0,   0, 270, 180) },
  { name: 'industrial',      label: 'Boiler Room',          ...z(  0, 180, 310, 210) },
  { name: 'pipe_corridor',   label: 'Pipe Corridor',        ...z(  0, 210,  45, 180) },
  { name: 'lobby',           label: 'Main Lobby / Atrium',  ...z(280,   0, 430, 390) },
  { name: 'tech_room_ne',    label: 'Tech Room',            ...z(710,   0, 170, 190) },
  { name: 'ne_connector',    label: 'NE Connector',         ...z(670,  80,  50, 110) },
  { name: 'far_right_top',   label: 'Far-Right Upper',      ...z(880,   0, 160,  80) },
  { name: 'office_e',        label: 'East Office',          ...z(780, 190, 170, 200) },
  { name: 'far_right_strip', label: 'Far-Right Strip',      ...z(950,  80,  90, 310) },
  { name: 'gas_station',     label: 'Gas Station',          ...z(  0, 390, 310, 190) },
  { name: 'park',            label: 'Outdoor Park',         ...z(310, 390, 400, 190) },
  { name: 'junction_s',      label: 'South Junction',       ...z(600, 360, 130, 130) },
  { name: 'garage_se',       label: 'Vehicle Garage',       ...z(730, 330, 140, 160) },
  { name: 'corridor_se',     label: 'SE Corridor',          ...z(870, 210,  50, 280) },
  { name: 'electrical',      label: 'Electrical Room',      ...z(730, 470, 190, 110) },
  { name: 'strip_far_se',    label: 'Far-SE Strip',         ...z(920, 320, 120, 260) },
];

// ─────────────────────────────────────────────────────────────────────────────
// Build the static collision grid
// ─────────────────────────────────────────────────────────────────────────────
let _cached: Grid | null = null;

export function buildCollisionGrid(): Grid {
  if (_cached) return _cached;
  // Decoded directly from the red-line reference image (see
  // scripts/src/analyzeCollisionMap.ts) — pixel-accurate, not hand-traced.
  _cached = decodeRuns();
  return _cached;
}

// ─────────────────────────────────────────────────────────────────────────────
// Query helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Is the cell at pixel (px, py) blocked? Returns true if outside map bounds. */
export function isBlocked(grid: Grid, px: number, py: number): boolean {
  const col = Math.floor(px / CELL_X);
  const row = Math.floor(py / CELL_Y);
  if (col < 0 || col >= COLS || row < 0 || row >= ROWS) return true;
  return grid[row * COLS + col] === 1;
}

/**
 * Can an entity with the given radius move to pixel position (cx, cy)?
 * Samples the center plus points around the circle's circumference — not
 * just the 4 cardinal points — so corners of blocked cells can't be cut
 * through during diagonal movement. Sample count scales with radius so the
 * arc length between samples stays well under one grid cell.
 */
export function canMoveTo(
  grid: Grid,
  cx: number, cy: number,
  radius = 8,
): boolean {
  if (isBlocked(grid, cx, cy)) return false;

  const minCell = Math.min(CELL_X, CELL_Y);
  const samples = Math.max(8, Math.ceil((2 * Math.PI * radius) / (minCell * 0.5)));
  for (let i = 0; i < samples; i++) {
    const angle = (i / samples) * Math.PI * 2;
    const px = cx + Math.cos(angle) * radius;
    const py = cy + Math.sin(angle) * radius;
    if (isBlocked(grid, px, py)) return false;
  }
  return true;
}

/**
 * Resolve movement: return the furthest reachable position when trying to
 * move from (x, y) to (nx, ny) with the given radius.  Slides along walls
 * by trying each axis independently.
 */
export function resolveMovement(
  grid: Grid,
  x: number,  y: number,
  nx: number, ny: number,
  radius = 8,
): [number, number] {
  // Try full move
  if (canMoveTo(grid, nx, ny, radius)) return [nx, ny];
  // Slide on X only
  if (canMoveTo(grid, nx, y, radius))  return [nx, y];
  // Slide on Y only
  if (canMoveTo(grid, x, ny, radius))  return [x, ny];
  // Stuck
  return [x, y];
}
